### ISSUE TITLE
Event Boundary Detection

### ISSUE THREAD

**Issue by adeljalalyousif** [GX77/Dual-Stream-Transformer-for-Generic-Event-Boundary-Captioning#2]
Hello, I am currently working on detecting event boundaries in videos from MSVD or MSR-VTT datasets. Unlike the ActivityNet dataset, these datasets lack timing information. Do you have any straightforward ideas or methods that could help me address this challenge?

**Comment by GX77** [comment]
The core of event boundary detection is to determine the key turning points in the video.&nbsp;You can refer "Local Compressed Video Stream Learning for Generic Event Boundary Detection".




GX
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GX77/Dual-Stream-Transformer-for-Generic-Event-Boundary-Captioning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月26日(星期天) 晚上7:37
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[GX77/Dual-Stream-Transformer-for-Generic-Event-Boundary-Captioning] Event Boundary Detection (Issue #2)





 
Hello, I am currently working on detecting event boundaries in videos from MSVD or MSR-VTT datasets. Unlike the ActivityNet dataset, these datasets lack timing information. Do you have any straightforward ideas or methods that could help me address this challenge?

**Comment by adeljalalyousif** [comment]
Thank you
